#!/bin/bash
#Regroupe des fichiers TPS à 1h-1s - PB 2015/10/18

if [ ! $# == 5 ]; then
  echo "Regroupe des fichiers TPS de 1h-1s"
  echo "Usage: $0 station an mois debut fin"; echo "Exemple: $0 meso 2015 08 12 14"
  exit
fi

for i in $(seq $4 $5)
  do
  if [ $i -lt 10 ]
    then
      j='0'$i
    else
      j=$i
  fi
  cat $1$3$j* > $1$2$3$j'0.tps'
  echo $1$2$3$j'0.tps'
done
