#!/bin/bash

#Recupere fichiers rinex sur le site du NOA

if [ ! $# == 4 ]; then
  echo "Recupere les fichiers de la station NOA specifiee"
  echo "Cas des donnees rangees par annee"
  echo "Usage : $0 stat year start stop"
  echo "Exemple: $0 RLSO 2011 1 100"
  exit
fi

#Parametres generaux des fichiers stockes sur le serveur du NOA
f='http://www.gein.noa.gr/services/GPSData/'

for x in $(seq $3 1 $4)
do
  st=`echo $1 | tr '[:upper:]' '[:lower:]'`
  yy=$(($x ))
  xx='00'$x
  zz=${xx: -3}
  b=$2
  bb=${b:2:2}
  aa=$st$zz'0.'$bb'd.Z'
  gg=$f$2/$zz/$aa
  echo $gg
  wget $gg
done
